%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2  

#imu_topic: "/imu_node/data"
imu_topic: "/mavros/imu/data"
image0_topic: "/stereo_s/left/image_raw"
image1_topic: "/stereo_s/right/image_raw"
output_path: "/home/nankel/Escort_Drone_ws/output/"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.02486997,  0.02881897,  0.99927521,  0.08802319,
          -0.9980696 ,  0.05618646, -0.02646037,  0.03087264,
          -0.0569083 , -0.99800428,  0.02736598, -0.02964395,
           0.        ,  0.        ,  0.        ,  1.        ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.02731351,  0.03073964,  0.99915417,  0.08594055,
          -0.99799661,  0.05622361, -0.02901162, -0.029215  ,
          -0.05706786, -0.99794488,  0.02914239, -0.03293779,
           0.        ,  0.        ,  0.        ,  1.        ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 100 #150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.03  # max solver itration time (ms), to guarantee real time # 0.04
max_num_iterations: 4   # max solver itrations, to guarantee real time  # 8
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.394749015573   # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.0143555686942 # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000483828798988 # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 1.24560931756e-05 # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8065500033         # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.0309666986227                # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/nankel/Escort_Drone_ws/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
